name: deploy dev
on:
  push:
    branches:
      - dev
      - feature/CI_CD_pipeline

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      DOCKER_HUB_USER_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      MONGO_PORT: ${{ secrets.MONGO_DEV_PORT }}
      EXPOSE_PORT: 8001
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Get semantic versioning
        id: versioning
        uses: paulhatch/semantic-version@v5.0.2
        with:   
          branch: dev
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE"
          minor_pattern: "feat"
          version_format: "${major}.${minor}.${patch}"
      -
        name: Update version in package.json and add tag to git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version v${{ steps.versioning.outputs.version }}
          git push --follow-tags 
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER_NAME }}/suigetsu-project:latest
      -
        name: Prepare the docker-compose run
        run: |
              ls -l
      - 
        name: Prepare docker-compose run
        run: |
              mkdir suigetsu-backend
              cp docker-compose.dev.yml suigetsu-project/docker-compose.dev.yml
              cd suigetsu-backend
              docker-compose -H ${{ secrets.DOCKER_HOST_SERVER }} -f docker-compose.dev.yml down
              docker-compose -H ${{ secrets.DOCKER_HOST_SERVER }} -f docker-compose.dev.yml pull
              docker-compose -H ${{ secrets.DOCKER_HOST_SERVER }} -f docker-compose.dev.yml up -d